import { describe, it, expect } from "bun:test";
import { setupBun } from "../src/actions/setup";
import { createSerializer } from "../src/render";
import { Workflow } from "../src/workflow-types";

const renderWorkflow = (workflow: Workflow) => {
  return createSerializer(workflow, Bun.YAML.stringify).stringifyWorkflow();
};

describe("setupBun", () => {
  it("should render with default options", () => {
    const workflow: Workflow = {
      name: "Test Workflow",
      on: "push",
      jobs: {
        test: {
          "runs-on": "ubuntu-latest",
          steps: [setupBun()],
        },
      },
    };
    expect(renderWorkflow(workflow)).toMatchInlineSnapshot(`
      "# Do not modify!
      # This file was generated by https://github.com/JLarky/gha-ts

      name: Test Workflow
      "on": push
      jobs: 
        test: 
          runs-on: ubuntu-latest
          steps: 
            - uses: oven-sh/setup-bun@v2
      "
    `);
  });

  it("should render with a specific bun version", () => {
    const workflow: Workflow = {
      name: "Test Workflow",
      on: "push",
      jobs: {
        test: {
          "runs-on": "ubuntu-latest",
          steps: [setupBun({ bunVersion: "1.0.0" })],
        },
      },
    };
    expect(renderWorkflow(workflow)).toMatchInlineSnapshot(`
      "# Do not modify!
      # This file was generated by https://github.com/JLarky/gha-ts

      name: Test Workflow
      "on": push
      jobs: 
        test: 
          runs-on: ubuntu-latest
          steps: 
            - uses: oven-sh/setup-bun@v2
              with: 
                bun-version: 1.0.0
      "
    `);
  });

  it("should render with all options", () => {
    const workflow: Workflow = {
      name: "Test Workflow",
      on: "push",
      jobs: {
        test: {
          "runs-on": "ubuntu-latest",
          steps: [
            setupBun({
              bunVersion: "latest",
              bunVersionFile: ".bun-version",
              bunDownloadUrl: "https://example.com/bun.zip",
              registryUrl: "https://registry.npmjs.org",
              scope: "@my-scope",
            }),
          ],
        },
      },
    };
    expect(renderWorkflow(workflow)).toMatchInlineSnapshot(`
      "# Do not modify!
      # This file was generated by https://github.com/JLarky/gha-ts

      name: Test Workflow
      "on": push
      jobs: 
        test: 
          runs-on: ubuntu-latest
          steps: 
            - uses: oven-sh/setup-bun@v2
              with: 
                bun-version: latest
                bun-version-file: .bun-version
                bun-download-url: https://example.com/bun.zip
                registry-url: https://registry.npmjs.org
                scope: "@my-scope"
      "
    `);
  });
});
