import type { Workflow, OnObject, Job } from "../workflow-types";
import {
  isDefaultJob,
  normalizeRunsOn,
  validateWorkflow,
} from "../workflow-types";

export const HEADER =
  "# Do not modify!\n# This file was generated by https://github.com/JLarky/gha-ts\n\n";

function normalizeSchedule(
  schedule: OnObject["schedule"],
): { cron: string }[] | undefined {
  if (!schedule) return undefined;
  if (Array.isArray(schedule)) {
    if (schedule.length === 0) return [];
    const first = schedule[0];
    if (typeof first === "string")
      return (schedule as string[]).map((c) => ({ cron: c }));
    if (typeof first === "object" && first && "cron" in first)
      return schedule as { cron: string }[];
  } else if (typeof schedule === "object" && schedule) {
    const s = schedule;
    if (Array.isArray(s.cron))
      return (s.cron as string[]).map((c) => ({ cron: c }));
  }
  return undefined;
}

function normalizeOn(on: Workflow["on"]): any {
  if (typeof on === "string" || Array.isArray(on)) return on;
  const obj: any = { ...on };
  if (obj.schedule !== undefined)
    obj.schedule = normalizeSchedule(obj.schedule);
  return obj;
}

function normalizeJobs(jobs: Record<string, Job>): Record<string, any> {
  const out: Record<string, any> = {};
  for (const [id, job] of Object.entries(jobs)) {
    if (isDefaultJob(job)) {
      out[id] = { ...job, ["runs-on"]: normalizeRunsOn(job["runs-on"]) };
    } else {
      out[id] = job;
    }
  }
  return out;
}

export function toYamlReadyObject(workflow: Workflow): Record<string, unknown> {
  validateWorkflow(workflow);
  const ordered: Record<string, unknown> = {};
  const obj = {
    name: workflow.name,
    "run-name": workflow["run-name"],
    on: normalizeOn(workflow.on),
    env: workflow.env,
    concurrency: workflow.concurrency,
    permissions: workflow.permissions,
    defaults: workflow.defaults,
    jobs: normalizeJobs(workflow.jobs),
  };

  // First, add known keys in the specified order
  const knownKeys = [
    "name",
    "run-name",
    "on",
    "env",
    "concurrency",
    "permissions",
    "defaults",
    "jobs",
  ];
  for (const key of knownKeys) {
    if (obj[key as keyof typeof obj] !== undefined)
      ordered[key] = obj[key as keyof typeof obj];
  }

  // Then, add any unknown/custom properties from the original workflow
  const unknownKeys: string[] = [];
  for (const key of Object.keys(workflow) as (keyof Workflow)[]) {
    if (!knownKeys.includes(key) && workflow[key] !== undefined) {
      unknownKeys.push(key);
      ordered[key] = workflow[key];
    }
  }

  if (unknownKeys.length > 0) {
    console.warn(
      `Warning: Unknown workflow properties detected: ${unknownKeys.join(", ")}. ` +
        `This may indicate a typo in your workflow or that gha-ts needs to be updated to support new GitHub Actions features.`,
    );
  }

  return ordered;
}
