name: CreateRelease
'on':
  push:
    tags:
    - '*'
permissions:
  contents: write
jobs:
  createRelease:
    runs-on: ubuntu-latest
    steps:
    - name: checkout
      uses: actions/checkout@v4
    - name: Install pkl cli and add to path
      run: |-
        curl -L -o pkl https://github.com/apple/pkl/releases/download/0.25.2/pkl-linux-amd64
        chmod +x pkl
        ./pkl --version

        mkdir -p $HOME/.local/bin
        mv pkl $HOME/.local/bin/pkl
        echo "$HOME/.local/bin" >> $GITHUB_PATH
    - name: Package pkl module
      env:
        VERSION: ${{ github.ref_name }}
      run: pkl project package
    - name: Rename pkl module
      run: |-
        VERSION_NUMBER=${{ github.ref_name }}
        VERSION_NUMBER=${VERSION_NUMBER#*@}
        echo "VERSION_NUMBER=$VERSION_NUMBER" >> $GITHUB_ENV
        for file in .out/com.github.action@$VERSION_NUMBER/pkl-gha*; do
          mv "$file" "${file/pkl-gha/com.github.action}"
        done
    - uses: softprops/action-gh-release@v1
      with:
        files: .out/com.github.action@${{ env.VERSION_NUMBER }}/*
        prerelease: 'true'
        draft: 'true'
